.eslintrc
.gitignore
.prettierrc.json
nodemon.json
package.json
src/index.ts
tsconfig.json

RPC Server Base

---

.gitignore
contracts/Scarb.toml
contracts/src/interface.cairo
contracts/src/lens.cairo
contracts/src/lib.cairo

contract base

---

.gitignore
contracts/src/interface.cairo
contracts/src/lens.cairo

Added Storage for Addresses + Getters

---

contracts/src/interface.cairo
contracts/src/lens.cairo

Completes https://github.com/keep-starknet-strange/rosettanet/issues/11

Register contract and tests

---

src/rpc/calls.ts
src/rpc/calls/chainId.ts
src/types/types.ts
src/utils/callHelper.ts
src/utils/parser.ts
tests/rpc/calls/chainId.test.ts
tests/rpc/chainId.test.ts

Completes both
https://github.com/keep-starknet-strange/rosettanet/issues/26
https://github.com/keep-starknet-strange/rosettanet/issues/20

chainId and rpc caller

---

.gitignore
src/utils/wrapper.ts

contract deployment

---

src/rpc/calls.ts
src/rpc/calls/maxPriorityFeePerGas.ts
tests/rpc/calls/maxPriorityFeePerGas.test.ts

Since there is no fee market. Simply return zero

maxPriorityFeePerGas call + tests

---

src/rpc/calls.ts
src/rpc/calls/getBalance.ts
src/utils/converters/integer.ts
tests/rpc/calls/getBalance.test.ts

feat : Implemented getBalance method

---

src/rpc/calls.ts
src/rpc/calls/getBlockTransactionCountByHash.ts
tests/rpc/calls/getBlockTransactionCountByHash.test.ts

Implementation for https://github.com/keep-starknet-strange/rosettanet/issues/65

Implement eth_getBlockTransactionCountByHash

---

package.json
src/utils/starknet.ts

getContractsMethods are implemented.
Issue: #55

feat: getContractsMethods implemented

---

package.json
src/utils/sn_keccak.ts
src/utils/starknet.ts
tests/utils/sn_keccak.test.ts
tests/utils/starknet.test.ts

Closes #56 
I also refactor add add test for issue #55 since it is directly related to my issue. Please check it out @ermvrs

Feat(utils): Add `generateEntrypointsSelector`

---

src/rpc/calls.ts
src/rpc/calls/feeHistory.ts
tests/rpc/calls/feeHistory.test.ts

Add `feeHistory` RPC method

---

src/rpc/calls/ethCall.ts
src/types/types.ts
src/utils/converters/calldata.ts
src/utils/starknet.ts
tests/utils/starknet.test.ts

First part of eth_call, still need to complete `getContractsMethods(...)` in starknet.ts.

`eth_call` Partial

---

src/utils/starknet.ts

Abi Array Fixes

---

src/rpc/calls/ethCall.ts
src/utils/converters/calldata.ts
src/utils/converters/typeConverters.ts
src/utils/match.ts
src/utils/starknet.ts
src/utils/wrapper.ts
tests/rpc/calls/ethCall.test.ts
tests/utils/converters/calldata.test.ts

Second part of eth_call done,
Now it matches the Ethereum selector with the function on the starknet target.

second part of eth_Call

---

src/rpc/calls.ts
src/rpc/calls/syncing.ts
tests/rpc/calls/syncing.test.ts

eth syncing method

---

src/rpc/calls/ethCall.ts
src/utils/calldata.ts
src/utils/converters/integer.ts
tests/rpc/calls/ethCall.test.ts
tests/utils/calldata.test.ts
tests/utils/converter.test.ts
tests/utils/converters/integer.test.ts
tests/utils/sn_keccak.test.ts

We successfully format Ethereum input and called the starknet function. The test includes balance of call on the constant address on starknet. 
The only part left is formatting the Ethereum response according to the starknet function output.

eth_Call, starknet request completes

---

tests/utils/converters/integer.test.ts
yarn.lock

Hey @ermvrs! 👋
Could you please check my commits out and let me know if there is a problem?

refactor: Add Uint256ToU256 and U256toUint256 conversion functions

---

src/rpc/calls.ts
src/rpc/calls/accounts.ts
tests/rpc/calls/accounts.test.ts
tests/utils/converters/integer.test.ts

eth_accounts implementation

---

src/rpc/calls.ts
src/types/types.ts

Unimplemented test code match with infura

---

.gitignore
package.json
src/logger.ts

logging commands

---

src/rpc/calls/getBlockByNumber.ts
src/rpc/calls/getCode.ts
src/rpc/calls/getTransactionByBlockNumberAndIndex.ts
tests/rpc/calls/getTransactionByBlockNumberAndIndex.test.ts

Adding validation of block number in request cant be higher than live block number

Adding validation for blockNumber

---

src/rpc/calls/feeHistory.ts
src/rpc/calls/gasPrice.ts
src/rpc/calls/getBalance.ts
src/rpc/calls/getBlockTransactionCountByHash.ts
src/rpc/calls/getStorageAt.ts
src/rpc/calls/getTransactionReceipt.ts
src/rpc/calls/netVersion.ts
src/rpc/calls/starknetCall.ts
src/rpc/calls/syncing.ts
tests/rpc/calls/gasPrice.test.ts
tests/rpc/calls/syncing.test.ts

Always returns same id with request

request id match with response

---

config.json
docs/methodsStatus.md
src/rpc/calls.ts
src/rpc/calls/blobBaseFee.ts
src/utils/callHelper.ts
src/utils/configReader.ts
src/utils/getRpc.ts
src/utils/starknet.ts
tests/rpc/calls/blobBaseFee.test.ts
tests/utils/configReader.test.ts
tests/utils/getRpc.test.ts
tests/utils/starknet.test.ts

Eth blob base fee implementation

---

docs/methodsStatus.md
src/rpc/calls.ts
src/rpc/calls/mining.ts
tests/rpc/calls/mining.test.ts

eth_mining implementation

---

docs/methodsStatus.md
src/rpc/calls.ts
src/rpc/calls/getWork.ts
tests/rpc/calls/getWork.test.ts

Eth get work implementation

---

docs/methodsStatus.md
src/rpc/calls.ts
src/rpc/calls/netListening.ts
tests/rpc/calls/netListening.test.ts

net_listening implementation

---

src/rpc/calls.ts
src/rpc/calls/web3clientVersion.ts
tests/rpc/calls/web3clientVersion.test.ts

implementation of web3_clientVersion

---

docs/methodsStatus.md
src/rpc/calls.ts
src/rpc/calls/netPeerCount.ts
tests/rpc/calls/netPeerCount.test.ts

implementation of net_peerCount

---

docs/methodsStatus.md
src/rpc/calls.ts
src/rpc/calls/getUncleByBlockNumberAndIndex.ts
tests/rpc/calls/getUncleByBlockNumberAndIndex.test.ts

implement eth_getUncleByBlockNumberAndIndex

---

docs/methodsStatus.md
src/rpc/calls.ts
src/rpc/calls/getUncleByBlockHashAndIndex.ts
tests/rpc/calls/getUncleByBlockHashAndIndex.test.ts
tests/rpc/calls/getUncleByBlockNumberAndIndex.test.ts

Eth get uncle by block hash and index

---

docs/methodsStatus.md
src/rpc/calls.ts
src/rpc/calls/getUncleCountByBlockHash.ts
tests/rpc/calls/getUncleCountByBlockHash.test.ts

Implement eth_getUncleCountByBlockHash

---

tests/rpc/calls/getUncleByBlockNumberAndIndex.test.ts

small tests fix

---

docs/methodsStatus.md
src/rpc/calls.ts
src/rpc/calls/unsubscribe.ts
tests/rpc/calls/unsubscribe.test.ts

implementation of eth_unsubscribe

---

config.json
src/rpc/calls/sendRawTransaction.ts
src/utils/callHelper.ts
src/utils/rosettanet.ts

rosetta account check, not completed. Will complete after account classes and factory deployment on sepolia

classhash check on sendrawtx

---

config.json
src/rpc/calls/sendRawTransaction.ts
src/types/types.ts
src/utils/converters/abiFormatter.ts
src/utils/directives.ts
src/utils/match.ts
src/utils/rosettanet.ts
src/utils/transaction.ts
src/utils/wrapper.ts
tests/rpc/calls/sendRawTransaction.test.ts
tests/testingUtilities.ts

Updates on config. New test utility

some updates

---

src/rpc/calls/sendRawTransaction.ts
src/types/transactions.types.ts
src/types/typeGuards.ts
src/types/types.ts
src/utils/callHelper.ts
src/utils/calldata.ts
src/utils/converters/integer.ts
src/utils/directives.ts
src/utils/rosettanet.ts
src/utils/signature.ts
src/utils/transaction.ts
src/utils/wrapper.ts
tests/rpc/calls/sendRawTransaction.test.ts

Starting with this PR. I'll refactor the whole codebase and remove unused features. Also we will update our method on eth_call
During the refactor, lint and tests may fail

Refactor #1

---

src/cache/blockNumber.ts
src/index.ts
src/rpc/calls/blockNumber.ts
src/utils/transaction.ts

Now we are caching starknet block number and holding in cached variable. It updates every 10 seconds. This reduces significant number of starknet rpc calls.

Cached block number reduced number of calls to Starknet RPC

---

src/cache/gasPrice.ts
src/index.ts
src/rpc/calls/estimateGas.ts
src/rpc/calls/gasPrice.ts
src/rpc/calls/getBalance.ts
src/rpc/calls/getBlockByNumber.ts
src/rpc/calls/sendRawTransaction.ts
src/types/typeGuards.ts
src/types/types.ts
src/utils/callHelper.ts
src/utils/transaction.ts
src/utils/validations.ts
src/utils/wrapper.ts
tests/rpc/calls/getBlockByNumber.test.ts

Gas price calculations

---

src/cache/gasPrice.ts
src/rpc/calls/getBalance.ts
src/rpc/calls/getTransactionReceipt.ts
src/rpc/calls/sendRawTransaction.ts
src/types/typeGuards.ts
src/utils/gas.ts
src/utils/rosettanet.ts
src/utils/wrapper.ts

Now we are also falling back to precalculated address if to address is not registered on rosettanet registry.

Transaction receipt fix

---

src/rpc/calls/getTransactionReceipt.ts
src/rpc/calls/sendRawTransaction.ts
src/utils/rosettanet.ts

Now account will be deployed on first transaction. User's first transaction will not be executed.

Deploy flow changed

---

src/rpc/calls/sendRawTransaction.ts
src/utils/calldata.ts
src/utils/transaction.ts
tests/utils/calldata.test.ts

Added specific calldata prepare function for multicall feature.

Internal function calls are now available
